model_list:
  - model_name: gpt-5.3-codex
    litellm_params:
      model: github_copilot/gpt-5.3-codex
      extra_headers: { "Editor-Version": "vscode/1.85.1", "Copilot-Integration-Id": "vscode-chat"}
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: github_copilot/claude-3-5-sonnet
      extra_headers: { "Editor-Version": "vscode/1.85.1", "Copilot-Integration-Id": "vscode-chat"}
